USE [master]
GO

/****** Object:  Database [Commerce]    Script Date: 9/7/2017 8:21:00 AM ******/
CREATE DATABASE [Commerce]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Commerce', FILENAME = N'D:\SQL\MSSQL13.SQLEXPRESS\MSSQL\DATA\Commerce.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Commerce_log', FILENAME = N'D:\SQL\MSSQL13.SQLEXPRESS\MSSQL\DATA\Commerce_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Commerce] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Commerce].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Commerce] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Commerce] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Commerce] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Commerce] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Commerce] SET ARITHABORT OFF 
GO

ALTER DATABASE [Commerce] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Commerce] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Commerce] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Commerce] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Commerce] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Commerce] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Commerce] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Commerce] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Commerce] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Commerce] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Commerce] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Commerce] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Commerce] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Commerce] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Commerce] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Commerce] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Commerce] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Commerce] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Commerce] SET  MULTI_USER 
GO

ALTER DATABASE [Commerce] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Commerce] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Commerce] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Commerce] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Commerce] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Commerce] SET QUERY_STORE = OFF
GO

USE [Commerce]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Commerce] SET  READ_WRITE 
GO


